import type { SchedulingLabels } from './schedulingTypes';

export const DEFAULT_SCHEDULING_LABELS: SchedulingLabels = {
  bookAppointment: 'Book appointment',
  newRecall: 'New recall',
  allProviders: 'All providers',
  showFilters: 'Show filters',
  hideFilters: 'Hide filters',
  flowBoardMode2Hint: 'Mode 2 arrivals only — use Front Desk Start visit & check in for the clinical queue.',
  calendarAppointments: 'appointments',
  loadingCalendar: 'Loading calendar…',
  loadingFlowBoard: 'Loading Flow Board…',
  lensCalendar: 'Calendar',
  lensFlow: 'Flow Board',
  lensRecalls: 'Recalls',
  calendarNoAppointments: 'No appointments for this day.',
  calendarSlotIntervals: 'Slot grid uses',
  calendarOn: 'on',
  calendarFrom: 'from',
  calendarTo: 'to',
  calendarAppointmentSingular: 'appointment',
  calendarDayGrid: 'Day grid',
  calendarAgenda: 'Agenda',
  calendarWeek: 'Week',
  calendarMonth: 'Month',
  frontDesk: 'Front Desk',
  close: 'Close',
  flowBoardBoard: 'Board',
  flowBoardList: 'List',
  flowBoardNoPatients: 'No patients',
  flowBoardNext: 'Next',
  flowBoardCheckIn: 'Check in',
  flowBoardRoomPrefix: 'Rm',
  moveLaneLeft: 'Move lane left',
  moveLaneRight: 'Move lane right',
  recallOverdue: 'Overdue',
  recallDue: 'Due now',
  recallUpcoming: 'Upcoming',
  recallCompleted: 'Completed',
  recallSearchPlaceholder: 'Search patient or reason',
  loadingRecalls: 'Loading recalls…',
  recallNoRows: 'No recalls in this bucket.',
  recallLogOutcome: 'Log outcome',
  recallBookAppt: 'Book appt',
  recallSnooze: 'Snooze 7d',
  recallEdit: 'Edit',
  recallDelete: 'Delete',
  errorLoadFlowBoard: 'Could not load Flow Board',
  errorStatusUpdate: 'Status update failed',
  errorRoomUpdate: 'Room update failed',
  errorLoadCalendar: 'Failed to load calendar',
  errorMoveAppointment: 'Could not move appointment',
  errorResizeAppointment: 'Could not resize appointment',
  errorLoadRecalls: 'Failed to load recalls',
  errorOpenBooking: 'Failed to open booking',
  errorBookingFailed: 'Booking failed',
  errorSaveFailed: 'Save failed',
  errorSnoozeFailed: 'Snooze failed',
  errorDeleteFailed: 'Delete failed',
  errorSendReminderFailed: 'Send reminder failed',
  bookSheetTitle: 'Book appointment',
  bookSheetAria: 'Book appointment',
  cancel: 'Cancel',
  saveAppointment: 'Save appointment',
  saving: 'Saving…',
  bookingHint: 'Mode 2 booking only — clinical check-in is still at Front Desk Start visit & check in.',
  patient: 'Patient',
  provider: 'Provider',
  category: 'Category',
  time: 'Time',
  durationMin: 'Duration (min)',
  comments: 'Comments',
  bookingValidation: 'Patient, provider, category, and time are required',
  recallSheetNew: 'New recall',
  recallSheetEdit: 'Edit recall',
  recallSheetAria: 'Recall form',
  saveRecall: 'Save recall',
  recallHint: 'H1-safe path — only recall fields are saved. Contact details are read-only on the worklist.',
  dueDate: 'Due date',
  reason: 'Reason',
  facility: 'Facility',
  recallValidation: 'Patient, due date, provider, and facility are required',
  createRecallTooltip: 'Create a new recall',
  bookTooltip: 'Book a new appointment',
  requiresAclTooltip: 'Requires patients/appt ACL',
  flowBoardUpdatedAt: 'Flow board updated at',
  recurringTrackerDisabled: 'Recurring — tracker updates disabled',
  recurringScopeTitle: 'Edit recurring appointment',
  recurringScopePrompt: 'Apply this change to:',
  recurringScopeCurrent: 'Only this occurrence',
  recurringScopeFuture: 'This and future occurrences',
  recurringScopeAll: 'All occurrences in the series',
  noClinicalVisit: 'No clinical visit',
  fix: 'Fix',
  roomFor: 'Room for',
  listColTime: 'Time',
  listColPatient: 'Patient',
  listColStatus: 'Status',
  listColWait: 'Wait',
  listColActions: 'Actions',
  selectedPatient: 'Selected',
  reasonPlaceholder: 'e.g. 6-month review',
  deleteRecallConfirm: 'Delete recall for',
  weekMoreEvents: 'more',
  resizeAppointmentAria: 'Resize appointment',
  crossLinkViewAppointment: 'View appointment',
  crossLinkViewRecalls: 'Recalls',
  crossLinkFlowBoard: 'Flow Board',
  outcomeModalTitle: 'Log recall outcome',
  outcomeModalConfirm: 'Save outcome',
  outcomeModalStatus: 'Status',
  outcomeModalNote: 'Note',
  recallColPatient: 'Patient',
  recallColDue: 'Due',
  recallColReason: 'Reason',
  recallColStatus: 'Status',
  recallColContact: 'Contact',
  recallColActions: 'Actions',
  filteredPatientPid: 'Filtered to patient PID',
  recallType: 'Recall type',
  recallSendReminder: 'Send reminder',
  notifyPatientTitle: 'Notify patient?',
  notifyPatientBody: 'MedEx is enabled. Do you want to notify the patient about this schedule change?',
  notifyPatientConfirm: 'Notify patient',
  notifyPatientSkip: 'Save without notify',
  notifyPatientAbort: 'Cancel change',
  notifyMoveLabel: 'Move appointment',
  notifyResizeLabel: 'Resize appointment',
};

export function resolveSchedulingLabels(labels?: Partial<SchedulingLabels>): SchedulingLabels {
  return { ...DEFAULT_SCHEDULING_LABELS, ...labels };
}

export function recallBucketLabel(labels: SchedulingLabels, bucket: string): string {
  if (bucket === 'overdue') return labels.recallOverdue;
  if (bucket === 'due') return labels.recallDue;
  if (bucket === 'upcoming') return labels.recallUpcoming;
  if (bucket === 'completed') return labels.recallCompleted;
  return bucket;
}
