/**
 * New Clinic island i18n runtime (GAP-D / D1).
 *
 * Model mirrors core PHP `xl()`: the English source string IS the key.
 * `t('Save')` looks the string up in the active locale's dictionary and
 * falls back to the English text when there is no dictionary, no entry,
 * or an empty entry — so English needs no dictionary at all and an
 * untranslated string can never blank out a desk.
 *
 * Locale plumbing:
 * - PHP (`ShellLocaleService` via `PageController::emitPage`) resolves the
 *   session user's language (`$_SESSION['language_choice']` →
 *   `lang_languages.lang_code`) and stamps `data-lang-code` +
 *   `data-i18n-url` on the `#nc-t1` shell root. `data-i18n-url` is empty
 *   for English or when no dictionary file exists for the locale.
 * - `mountIsland()` awaits `ensureI18nReady()` before rendering, so by
 *   render time the dictionary (if any) is loaded. Because module-scope
 *   code runs at import time — BEFORE the dictionary can load — never
 *   call `t()` in module-scope constants; call it at render time
 *   (convert label constants to functions).
 *
 * Dictionaries are flat JSON objects (`{"English source": "Translation"}`)
 * served from the module's hand-managed `public/assets/i18n/<code>.json`
 * (NOT `assets/modern/`, which Vite wipes on every build). The key
 * inventory is generated by `npm run i18n:extract`
 * (frontend/scripts/extract-i18n.mjs).
 *
 * Interpolation: `t('Showing {start} of {total}', { start, total })`
 * replaces every `{name}` occurrence AFTER translation, so translators
 * can reorder placeholders. No plural rules in V1 (English-only ships);
 * phrase around plurals or pass precomputed words.
 */

export type I18nDictionary = Record<string, string>;
export type I18nParams = Record<string, string | number>;

let dictionary: I18nDictionary = {};
let langCode = 'en';
let readyPromise: Promise<void> | null = null;

/**
 * Translate a UI string. `message` must be a literal English string
 * (the extraction script reads it statically — never build keys at
 * runtime). Returns the translation, or the English text when none.
 */
export function t(message: string, params?: I18nParams): string {
  const translated = dictionary[message];
  let out = translated !== undefined && translated !== '' ? translated : message;
  if (params !== undefined) {
    for (const [name, value] of Object.entries(params)) {
      out = out.split(`{${name}}`).join(String(value));
    }
  }
  return out;
}

/** Active locale code ('en' until a dictionary locale is loaded). */
export function getLangCode(): string {
  return langCode;
}

/**
 * Load the page's dictionary once (memoized). Safe to call repeatedly;
 * all callers share one fetch. English (or a missing/failed dictionary)
 * resolves immediately and keeps the pass-through behavior.
 */
export function ensureI18nReady(): Promise<void> {
  readyPromise ??= loadFromPage();
  return readyPromise;
}

async function loadFromPage(): Promise<void> {
  const shell = document.querySelector<HTMLElement>('#nc-t1');
  const code = shell?.dataset.langCode?.trim() ?? '';
  const url = shell?.dataset.i18nUrl?.trim() ?? '';
  if (code !== '') langCode = code;
  if (url === '' || code === 'en' || code === '') return;

  try {
    const response = await fetch(url, { credentials: 'same-origin' });
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }
    const data: unknown = await response.json();
    if (data !== null && typeof data === 'object' && !Array.isArray(data)) {
      const entries = Object.entries(data as Record<string, unknown>).filter(
        (entry): entry is [string, string] => typeof entry[1] === 'string'
      );
      dictionary = Object.fromEntries(entries);
    }
  } catch (err) {
    // Fail open: an English desk beats a blank one. Same philosophy as
    // core xl(): missing translation → source string.
    console.error('[nc-i18n] failed to load dictionary', { url, err });
  }
}

/** Test-only: install a dictionary/locale without touching the DOM. */
export function __setI18nForTests(dict: I18nDictionary, code = 'en'): void {
  dictionary = dict;
  langCode = code;
}

/** Test-only: restore pristine English pass-through state. */
export function __resetI18nForTests(): void {
  dictionary = {};
  langCode = 'en';
  readyPromise = null;
}
